

const User = Object.freeze({
    name: { type: 'string', required: true },
    email: { type: 'string', required: true },
    username: { type: 'string', required: true },
    password: { type: 'string', required: true },

    surname: { type: 'string', required: false },
    phone: { type: 'string', required: false },
    
    _id: { type: 'object', required: false }, // new ObjectId() - Generated by server or bd
    date: { type: 'date', required: false }, // new date() - Generated by server or bd 

    type: { type: 'string', required: false }, // "free" - Generated by server
    token: { type: 'string', required: false }, // string
})

export default User